### PR TITLE
chmod +x deploy scripts

### PR DESCRIPTION
**Pull request by Nemo157**

### CODE REVIEW

**Comment by critiqjo** [comment]
Woops! :smile:

**Comment by Nemo157** [comment]
This is always the problem with using travis to deploy, can't test locally so have to just keep pushing changes till it works :cry:.

**Comment by critiqjo** [comment]
Crap! Reset the crates token? And don't pass it as arguments... Use environment variables only! https://travis-ci.org/Nemo157/hamlet/jobs/121919523

If it fails, it's printing them!

**Comment by critiqjo** [comment]
I think the scripts can access those as environment variables, right? Both `GITHUB_TOKEN` and `CRATES_IO_TOKEN`?

**Comment by Nemo157** [comment]
That's annoying, and since crates.io only supports a single token I need to replace it in all my other deploy scripts too :sob:. Yep they should be able to, not sure why I passed them as arguments really.

**Pull request merged**
