### PR TITLE
Rename to hamlet

### LINKED ISSUE #3: Rename the repo?
What I could come up with: html-duck, html-dodge, hornbill, hairtail, hamlet, ...

Suggest more and let's choose one...

### PR DESCRIPTION
**Pull request by Nemo157**
Closes #3.

@critiqjo also added you to the authors list based on your commit author line, want to use your real name or that good?

### CODE REVIEW

**Comment by critiqjo** [comment]
Guess it's fine, since the real name is obvious from the email! :sweat_smile:

**Comment by critiqjo** [comment]
:+1: Don't forget to reserve the crate name!!

**Comment by Nemo157** [comment]
Done, if you want owner access to it just create a crates.io account and let me know.

**Comment by critiqjo** [comment]
Oh! Thanks! I've logged in with Github. Now how do you find me on crates.io? API key or something?

**Comment by Nemo157** [comment]
Just github username, you should have access now.

**Comment by critiqjo** [comment]
Great! :+1:

**Pull request merged**
